name: thehiddensoulofcapitalism.com
favicon: null
layout_spectrum: 0.25467
typography_spectrum: 1
title: The Hidden Soul Of Capitalism
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060705'
    - '#4e6f62'
    - '#322b12'
    - '#abaf3e'
    - '#e7ed47'
  brandStrength: 0.944150363560766
  lightness: 0.8650436182506382
  saturation: 0.8590232427231967
  rhythmicContrast: 0.1664522693026811
purpose: []
